CREATE TABLE Program (
  ID SERIAL PRIMARY KEY,
  ProgramTitle VARCHAR(50) NOT NULL
);

CREATE TABLE Credit (
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Occupation VARCHAR(50) NOT NULL,
  Program_ID INTEGER NOT NULL REFERENCES Program(ID)
);

CREATE TABLE Login (
  ID SERIAL PRIMARY KEY,
  Username VARCHAR(50) UNIQUE NOT NULL,
  Password VARCHAR(50) NOT NULL,
  Authlvl INTEGER NOT NULL
);
